vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

get_filename_component(SOURCE_PATH "${CURRENT_PORT_DIR}/../.." ABSOLUTE)

set(KARMA_BUILD_SERVER_PROFILE OFF)
set(KARMA_BUILD_HEADLESS_PROFILE OFF)
set(KARMA_BUILD_GRAPHICAL_PROFILE OFF)
set(KARMA_NETWORK_BACKEND_ENET OFF)
set(KARMA_ENABLE_NAVIGATION OFF)
set(KARMA_PHYSICS_BACKEND_JOLT OFF)
set(KARMA_PHYSICS_BACKEND_BULLET OFF)

if("server" IN_LIST FEATURES)
  set(KARMA_BUILD_SERVER_PROFILE ON)
endif()
if("headless" IN_LIST FEATURES)
  set(KARMA_BUILD_HEADLESS_PROFILE ON)
endif()
if("graphical" IN_LIST FEATURES)
  set(KARMA_BUILD_GRAPHICAL_PROFILE ON)
endif()
if("network" IN_LIST FEATURES)
  set(KARMA_NETWORK_BACKEND_ENET ON)
endif()
if("navigation" IN_LIST FEATURES)
  set(KARMA_ENABLE_NAVIGATION ON)
endif()
if("physics-jolt" IN_LIST FEATURES)
  set(KARMA_PHYSICS_BACKEND_JOLT ON)
endif()
if("physics-bullet" IN_LIST FEATURES)
  set(KARMA_PHYSICS_BACKEND_BULLET ON)
endif()

if(NOT KARMA_BUILD_SERVER_PROFILE AND NOT KARMA_BUILD_HEADLESS_PROFILE AND NOT KARMA_BUILD_GRAPHICAL_PROFILE)
  message(FATAL_ERROR "The karma vcpkg port requires at least one profile feature: server, headless, or graphical.")
endif()

if(KARMA_PHYSICS_BACKEND_JOLT AND KARMA_PHYSICS_BACKEND_BULLET)
  message(FATAL_ERROR "Choose only one Karma physics backend feature: physics-jolt or physics-bullet.")
endif()

vcpkg_cmake_configure(
  SOURCE_PATH "${SOURCE_PATH}"
  OPTIONS
    -DKARMA_FETCH_DEPS=OFF
    -DKARMA_BUILD_SERVER_PROFILE=${KARMA_BUILD_SERVER_PROFILE}
    -DKARMA_BUILD_HEADLESS_PROFILE=${KARMA_BUILD_HEADLESS_PROFILE}
    -DKARMA_BUILD_GRAPHICAL_PROFILE=${KARMA_BUILD_GRAPHICAL_PROFILE}
    -DKARMA_NETWORK_BACKEND_ENET=${KARMA_NETWORK_BACKEND_ENET}
    -DKARMA_ENABLE_NAVIGATION=${KARMA_ENABLE_NAVIGATION}
    -DKARMA_PHYSICS_BACKEND_JOLT=${KARMA_PHYSICS_BACKEND_JOLT}
    -DKARMA_PHYSICS_BACKEND_BULLET=${KARMA_PHYSICS_BACKEND_BULLET}
    -DKARMA_BUILD_EXAMPLES=OFF
    -DKARMA_BUILD_TESTS=OFF
    -DBUILD_TESTING=OFF
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup(PACKAGE_NAME karma CONFIG_PATH lib/cmake/karma)
vcpkg_copy_pdbs()

file(REMOVE_RECURSE
  "${CURRENT_PACKAGES_DIR}/debug/include"
  "${CURRENT_PACKAGES_DIR}/debug/share"
)

configure_file("${CMAKE_CURRENT_LIST_DIR}/usage" "${CURRENT_PACKAGES_DIR}/share/${PORT}/usage" COPYONLY)
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
