if (NOT DEFINED KARMA_IS_TOP_LEVEL)
  if (CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
    set(KARMA_IS_TOP_LEVEL ON)
  else()
    set(KARMA_IS_TOP_LEVEL OFF)
  endif()
endif()

option(KARMA_HEADLESS "Build only the server/non-visual Karma profile" OFF)

set(KARMA_BUILD_GRAPHICAL_PROFILE_DEFAULT ON)
if (KARMA_HEADLESS)
  set(KARMA_BUILD_GRAPHICAL_PROFILE_DEFAULT OFF)
endif()
option(KARMA_BUILD_SERVER_PROFILE "Build the minimal karma::server networking profile target" ON)
option(KARMA_BUILD_HEADLESS_PROFILE "Build the karma::headless profile target" ON)
option(KARMA_BUILD_GRAPHICAL_PROFILE "Build the karma::graphical profile target" ${KARMA_BUILD_GRAPHICAL_PROFILE_DEFAULT})

option(KARMA_WINDOW_BACKEND_GLFW "Use GLFW window backend for the graphical profile" ON)
option(KARMA_WINDOW_BACKEND_SDL "Use SDL window backend for the graphical profile" OFF)
option(KARMA_RENDER_BACKEND_DILIGENT "Use Diligent renderer backend for the graphical profile" ON)
option(KARMA_ENABLE_AUDIO "Enable runtime audio through the selected backend" ON)
option(KARMA_AUDIO_BACKEND_MINIAUDIO "Use miniaudio backend" ON)
option(KARMA_AUDIO_BACKEND_SDL "Use SDL audio backend" OFF)
option(KARMA_NETWORK_BACKEND_ENET "Use ENet network backend" ON)
option(KARMA_PHYSICS_BACKEND_JOLT "Use Jolt physics backend" ON)
option(KARMA_PHYSICS_BACKEND_BULLET "Use Bullet physics backend" OFF)
option(KARMA_ENABLE_NAVIGATION "Build Recast/Detour navigation support" ON)
option(KARMA_ENABLE_KTX2 "Enable KTX2/BasisU texture compression support" ON)
option(KARMA_FETCH_DEPS "Fetch third-party dependencies if missing" ON)
option(KARMA_ASSIMP_MINIMAL_IMPORTERS
  "When fetching Assimp, build only GLTF/GLB, FBX, OBJ, and STL import support" ON)
option(KARMA_ENABLE_NATIVE_UI "Build Karma's first-party retained-mode UI" ${KARMA_BUILD_GRAPHICAL_PROFILE})
option(KARMA_ENABLE_IMGUI "Build the optional ImGui adapter and tooling" OFF)
option(KARMA_BUILD_DEBUG_UI "Build engine debug UI overlay" ${KARMA_ENABLE_IMGUI})
option(KARMA_BUILD_EXAMPLES "Build Karma example executables" ${KARMA_IS_TOP_LEVEL})
option(KARMA_BUILD_TESTS "Build Karma test executables" ${KARMA_IS_TOP_LEVEL})
option(KARMA_BUILD_TOOLS "Build Karma command-line content tools" ${KARMA_IS_TOP_LEVEL})
option(KARMA_INSTALL_VCPKG_DEPS
  "Install the active vcpkg triplet contents into the Karma install prefix for SDK packages" OFF)
option(KARMA_BUILD_IMGUI_DEMO "Build ImGui UI demo" ${KARMA_ENABLE_IMGUI})
option(KARMA_BUILD_RMLUI_DEMO "Build RmlUi UI demo" OFF)
option(KARMA_ENABLE_RMLUI "Build RmlUi UI adapter" OFF)
option(KARMA_DILIGENT_REPACK_XXHASH
  "Repack Diligent's bundled xxHash archive on affected Unix toolchains" OFF)
option(KARMA_DILIGENT_STRIP_RELEASE_O1
  "Remove Diligent's GCC Release -O1 interface option so CMAKE_*_RELEASE optimization flags apply" OFF)
set(KARMA_DILIGENT_TAG "v2.5.5" CACHE STRING "DiligentCore git tag/branch to fetch")
set(KARMA_JOLT_TAG "v5.5.0" CACHE STRING "JoltPhysics git tag/branch to fetch")
set(KARMA_KTX_SOFTWARE_TAG "v4.4.2" CACHE STRING "KTX-Software git tag/branch to fetch")

if (KARMA_HEADLESS)
  set(KARMA_BUILD_HEADLESS_PROFILE ON CACHE BOOL "Build the karma::headless profile target" FORCE)
  set(KARMA_BUILD_GRAPHICAL_PROFILE OFF CACHE BOOL "Build the karma::graphical profile target" FORCE)
endif()

if (KARMA_BUILD_RMLUI_DEMO)
  set(KARMA_ENABLE_RMLUI ON CACHE BOOL "Build RmlUi UI adapter" FORCE)
endif()

if (NOT KARMA_ENABLE_IMGUI)
  set(KARMA_BUILD_DEBUG_UI OFF CACHE BOOL "Build engine debug UI overlay" FORCE)
  set(KARMA_BUILD_IMGUI_DEMO OFF CACHE BOOL "Build ImGui UI demo" FORCE)
endif()

if (NOT KARMA_BUILD_GRAPHICAL_PROFILE)
  set(KARMA_WINDOW_BACKEND_GLFW OFF CACHE BOOL "Use GLFW window backend for the graphical profile" FORCE)
  set(KARMA_WINDOW_BACKEND_SDL OFF CACHE BOOL "Use SDL window backend for the graphical profile" FORCE)
  set(KARMA_RENDER_BACKEND_DILIGENT OFF CACHE BOOL "Use Diligent renderer backend for the graphical profile" FORCE)
  set(KARMA_ENABLE_AUDIO OFF CACHE BOOL "Enable runtime audio through the selected backend" FORCE)
  set(KARMA_ENABLE_NATIVE_UI OFF CACHE BOOL "Build Karma's first-party retained-mode UI" FORCE)
  set(KARMA_ENABLE_IMGUI OFF CACHE BOOL "Build the optional ImGui adapter and tooling" FORCE)
  set(KARMA_BUILD_DEBUG_UI OFF CACHE BOOL "Build engine debug UI overlay" FORCE)
  set(KARMA_BUILD_IMGUI_DEMO OFF CACHE BOOL "Build ImGui UI demo" FORCE)
  set(KARMA_BUILD_RMLUI_DEMO OFF CACHE BOOL "Build RmlUi UI demo" FORCE)
  set(KARMA_ENABLE_RMLUI OFF CACHE BOOL "Build RmlUi UI adapter" FORCE)
endif()

if (NOT KARMA_ENABLE_AUDIO)
  set(KARMA_AUDIO_BACKEND_MINIAUDIO OFF CACHE BOOL "Use miniaudio backend" FORCE)
  set(KARMA_AUDIO_BACKEND_SDL OFF CACHE BOOL "Use SDL audio backend" FORCE)
endif()

if (NOT KARMA_BUILD_SERVER_PROFILE AND NOT KARMA_BUILD_HEADLESS_PROFILE AND NOT KARMA_BUILD_GRAPHICAL_PROFILE)
  message(FATAL_ERROR "Enable at least one Karma consumer profile: KARMA_BUILD_SERVER_PROFILE, KARMA_BUILD_HEADLESS_PROFILE, or KARMA_BUILD_GRAPHICAL_PROFILE.")
endif()
if (KARMA_WINDOW_BACKEND_GLFW AND KARMA_WINDOW_BACKEND_SDL)
  message(FATAL_ERROR "Choose only one window backend: GLFW or SDL.")
endif()
if (KARMA_BUILD_GRAPHICAL_PROFILE AND NOT KARMA_WINDOW_BACKEND_GLFW AND NOT KARMA_WINDOW_BACKEND_SDL)
  message(FATAL_ERROR "Choose one window backend (GLFW or SDL), or disable KARMA_BUILD_GRAPHICAL_PROFILE.")
endif()
if (KARMA_AUDIO_BACKEND_MINIAUDIO AND KARMA_AUDIO_BACKEND_SDL)
  message(FATAL_ERROR "Choose only one audio backend: miniaudio or SDL.")
endif()
if (KARMA_BUILD_GRAPHICAL_PROFILE AND KARMA_ENABLE_AUDIO AND NOT KARMA_AUDIO_BACKEND_MINIAUDIO AND NOT KARMA_AUDIO_BACKEND_SDL)
  message(FATAL_ERROR "KARMA_ENABLE_AUDIO=ON requires one audio backend: miniaudio or SDL.")
endif()
if (KARMA_PHYSICS_BACKEND_JOLT AND KARMA_PHYSICS_BACKEND_BULLET)
  message(FATAL_ERROR "Choose only one physics backend: Jolt or Bullet.")
endif()
