option(KARMA_WINDOW_BACKEND_GLFW "Use GLFW window backend" ON)
option(KARMA_WINDOW_BACKEND_SDL "Use SDL window backend" OFF)
option(KARMA_RENDER_BACKEND_DILIGENT "Use Diligent renderer backend" ON)
option(KARMA_AUDIO_BACKEND_MINIAUDIO "Use miniaudio backend" ON)
option(KARMA_AUDIO_BACKEND_SDL "Use SDL audio backend" OFF)
option(KARMA_NETWORK_BACKEND_ENET "Use ENet network backend" ON)
option(KARMA_PHYSICS_BACKEND_JOLT "Use Jolt physics backend" ON)
option(KARMA_PHYSICS_BACKEND_BULLET "Use Bullet physics backend" OFF)
option(KARMA_ENABLE_NAVIGATION "Build Recast/Detour navigation support" ON)
option(KARMA_FETCH_DEPS "Fetch third-party dependencies if missing" ON)
option(KARMA_BUILD_DEBUG_UI "Build engine debug UI overlay" ON)
option(KARMA_BUILD_IMGUI_DEMO "Build ImGui UI demo" ON)
option(KARMA_BUILD_RMLUI_DEMO "Build RmlUi UI demo" ON)
option(KARMA_HEADLESS "Build without window/render backends and graphics demos" OFF)
set(KARMA_DILIGENT_TAG "v2.5.5" CACHE STRING "DiligentCore git tag/branch to fetch")

if (KARMA_HEADLESS)
  set(KARMA_WINDOW_BACKEND_GLFW OFF CACHE BOOL "Use GLFW window backend" FORCE)
  set(KARMA_WINDOW_BACKEND_SDL OFF CACHE BOOL "Use SDL window backend" FORCE)
  set(KARMA_RENDER_BACKEND_DILIGENT OFF CACHE BOOL "Use Diligent renderer backend" FORCE)
  set(KARMA_BUILD_DEBUG_UI OFF CACHE BOOL "Build engine debug UI overlay" FORCE)
  set(KARMA_BUILD_IMGUI_DEMO OFF CACHE BOOL "Build ImGui UI demo" FORCE)
  set(KARMA_BUILD_RMLUI_DEMO OFF CACHE BOOL "Build RmlUi UI demo" FORCE)
endif()

if (KARMA_WINDOW_BACKEND_GLFW AND KARMA_WINDOW_BACKEND_SDL)
  message(FATAL_ERROR "Choose only one window backend: GLFW or SDL.")
endif()
if (NOT KARMA_HEADLESS AND NOT KARMA_WINDOW_BACKEND_GLFW AND NOT KARMA_WINDOW_BACKEND_SDL)
  message(FATAL_ERROR "Choose one window backend (GLFW or SDL), or enable KARMA_HEADLESS.")
endif()
if (KARMA_AUDIO_BACKEND_MINIAUDIO AND KARMA_AUDIO_BACKEND_SDL)
  message(FATAL_ERROR "Choose only one audio backend: miniaudio or SDL.")
endif()
